#!/usr/bin/env bash

# Source the common helpers script.
source scripts/common.bash

# add -s for verbose output

printf "${yellow}"
print_banner "Python 3"
printf "${normal}"

find . -name "__pycache__" -exec rm -rf {} \; >& /dev/null
find . -name "*.py?" -exec rm {} \;           >& /dev/null

#if [ -e tests ]; then
#    rm -rf tests
#fi

options=(
    --cov-report
    term-missing
    --cov-report html
    --cov=configparserenhanced
    )
python3 -m pytest ${options[@]}
err=$?
echo -e ""
if [ $err != 0 ]; then
    echo -e "${red}======================${normal}"
    echo -e "${red}=== TESTING FAILED ===${normal}"
    echo -e "${red}======================${normal}"
else
    echo -e "${green}======================${normal}"
    echo -e "${green}=== TESTING PASSED ===${normal}"
    echo -e "${green}======================${normal}"
fi
echo -e ""

# Clean up generated bytecode
find . -name "__pycache__" -exec rm -rf {} \; >& /dev/null
find . -name "*.py?" -exec rm {} \;           >& /dev/null

exit $err
