#!/usr/bin/env bash

# Source the common helpers script.
source scripts/common.bash


execute_command_checked "./exec-reqs-install.sh"

# add -s for verbose output

printf "${yellow}"
print_banner "Python 3"
printf "${normal}\n"

find . -name "__pycache__" -exec rm -rf {} \; >& /dev/null
find . -name "*.py?" -exec rm {} \;           >& /dev/null

#if [ -e tests ]; then
#    rm -rf tests
#fi

options=(
    --cov-report=term
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml
    --cov=configparserenhanced
    )

python3 -m pytest ${options[@]}

err=$?
echo -e ""
if [ $err != 0 ]; then
    printf "${red}"
    print_banner "TESTING FAILED"
    printf "${normal}"
else
    printf "${green}"
    print_banner "TESTING PASSED"
    printf "${normal}"
fi
echo -e ""


execute_command_checked "python3 ./exec-example-ConfigParserEnhanced.py >& /dev/null"


# Clean up generated bytecode
find . -name "__pycache__" -exec rm -rf {} \; >& /dev/null
find . -name "*.py?" -exec rm {} \;           >& /dev/null

exit $err
