#!/usr/bin/env bash

# Source the common helpers script.
source scripts/common.bash

printf "${yellow}"
print_banner "Testing SetEnvironment"
printf "${normal}\n"

opt_venv='--user'
if [ ! -z ${VIRTUAL_ENV} ]; then
    message_std "Virtual environment ${green}detected${normal}."
    opt_venv=''
else
    message_std "Virtual environment ${red}not detected${normal}."
fi
printf "\n"


execute_command_checked "./exec-reqs-install.sh"


# add -s for verbose output

find . -name "__pycache__" -exec rm -rf {} \; >& /dev/null
find . -name "*.py?" -exec rm {} \;           >& /dev/null

#if [ -e tests ]; then
#    rm -rf tests
#fi

printf "${yellow}"
print_banner "Execute Tests"
printf "${normal}\n"

options=(
    --cov=setenvironment
    --cov-report=term
    #--cov-report=term-missing
    --cov-report=html
    --cov-report=xml
    --cov-config=.coveragerc
    )


python3 -m pytest ${options[@]}
err=$?


printf "\n"
if [ $err != 0 ]; then
    printf "${red}"
    print_banner "TESTING FAILED"
    printf "${normal}"
    exit $err
fi
printf "\n"


# Clean up generated bytecode
find . -name "__pycache__" -exec rm -rf {} \; >& /dev/null
find . -name "*.py?" -exec rm {} \;           >& /dev/null

printf "\n"
printf "${green}"
print_banner "TESTING PASSED"
printf "${normal}"
printf "\n"
