#!/usr/bin/env bash

find . -name "*.py?" -exec rm {} \;
find . -name "*.*,cover" -exec rm {} \;
find . -name "__pycache__" -exec rm -rf {} \;
find . -name ".DS_Store" -exec rm {} \;
find . -name "._.DS_Store" -exec rm {} \;

# remove 'temp' files generated by testing
find . -name "___config*.sh" -exec rm {} \;
find . -name "___config*.py" -exec rm {} \;

rm -rf build                > /dev/null 2>&1
rm -rf tests                > /dev/null 2>&1
rm -rf dist                 > /dev/null 2>&1
rm -rf doc/html             > /dev/null 2>&1
rm -rf .pytest_cache        > /dev/null 2>&1
rm     .coverage            > /dev/null 2>&1
rm ___*.sh                  > /dev/null 2>&1
rm ___*.py                  > /dev/null 2>&1
