#!/usr/bin/env bash

# Source the common helpers script.
source scripts/common.bash


execute_command_checked "./exec-reqs-install.sh"

# add -s for verbose output

printf "${yellow}"
print_banner "Python 3"
printf "${normal}"

find . -name "__pycache__" -exec rm -rf {} \; >& /dev/null
find . -name "*.py?" -exec rm {} \;           >& /dev/null

#if [ -e tests ]; then
#    rm -rf tests
#fi

options=(
    --cov-report
    term-missing
    --cov-report html
    --cov=configparserenhanced
    )


python3 -m pytest ${options[@]}

err=$?
echo -e ""
if [ $err != 0 ]; then
    print_banner "TESTING FAILED"
else
    print_banner "TESTING PASSED"
fi
echo -e ""

# Clean up generated bytecode
find . -name "__pycache__" -exec rm -rf {} \; >& /dev/null
find . -name "*.py?" -exec rm {} \;           >& /dev/null

exit $err
